#!/bin/bash

##############################################################################
# Maxun Chat Automation Quick Deploy Script
##############################################################################
#
# This script helps you quickly deploy Maxun for chat automation use cases.
#
# Usage:
#   ./deploy_chat_automation.sh
#
##############################################################################

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Print banner
print_banner() {
    echo -e "${BLUE}"
    cat << "EOF"
╔═══════════════════════════════════════════════════════════╗
║                                                           ║
║   __  __                                                  ║
║  |  \/  | __ ___  ___   _ _ __                           ║
║  | |\/| |/ _` \ \/ / | | | '_ \                          ║
║  | |  | | (_| |>  <| |_| | | | |                         ║
║  |_|  |_|\__,_/_/\_\\__,_|_| |_|                         ║
║                                                           ║
║   Chat Automation Quick Deploy                           ║
║                                                           ║
╚═══════════════════════════════════════════════════════════╝
EOF
    echo -e "${NC}"
}

# Check dependencies
check_dependencies() {
    echo -e "${BLUE}Checking dependencies...${NC}"
    
    if ! command -v docker &> /dev/null; then
        echo -e "${RED}✗ Docker is not installed${NC}"
        echo "Please install Docker: https://docs.docker.com/get-docker/"
        exit 1
    fi
    echo -e "${GREEN}✓ Docker found${NC}"
    
    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
        echo -e "${RED}✗ Docker Compose is not installed${NC}"
        echo "Please install Docker Compose: https://docs.docker.com/compose/install/"
        exit 1
    fi
    echo -e "${GREEN}✓ Docker Compose found${NC}"
    
    if ! command -v openssl &> /dev/null; then
        echo -e "${YELLOW}⚠ OpenSSL not found (optional but recommended)${NC}"
    else
        echo -e "${GREEN}✓ OpenSSL found${NC}"
    fi
    
    echo ""
}

# Generate secure random string
generate_secret() {
    if command -v openssl &> /dev/null; then
        openssl rand -hex 32
    else
        # Fallback if openssl not available
        cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1
    fi
}

# Setup environment file
setup_env() {
    echo -e "${BLUE}Setting up environment configuration...${NC}"
    
    if [ -f .env ]; then
        echo -e "${YELLOW}⚠ .env file already exists${NC}"
        read -p "Overwrite? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo -e "${YELLOW}Using existing .env file${NC}"
            return
        fi
    fi
    
    echo -e "${BLUE}Generating secure secrets...${NC}"
    
    JWT_SECRET=$(generate_secret)
    ENCRYPTION_KEY=$(generate_secret)
    SESSION_SECRET=$(generate_secret)
    MINIO_ACCESS=$(generate_secret | cut -c1-20)
    MINIO_SECRET=$(generate_secret)
    
    cat > .env << EOF
# Maxun Configuration - Auto-generated by deploy_chat_automation.sh
# Generated on: $(date)

# App Setup
NODE_ENV=production
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
SESSION_SECRET=${SESSION_SECRET}

# Database Configuration
DB_NAME=maxun
DB_USER=postgres
DB_PASSWORD=postgres
DB_HOST=postgres
DB_PORT=5432

# MinIO Object Storage
MINIO_ENDPOINT=minio
MINIO_PORT=9000
MINIO_CONSOLE_PORT=9001
MINIO_ACCESS_KEY=${MINIO_ACCESS}
MINIO_SECRET_KEY=${MINIO_SECRET}

# Redis Configuration
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=

# Backend and Frontend URLs and Ports
BACKEND_PORT=8080
FRONTEND_PORT=5173
BACKEND_URL=http://localhost:8080
PUBLIC_URL=http://localhost:5173
VITE_BACKEND_URL=http://localhost:8080
VITE_PUBLIC_URL=http://localhost:5173

# Optional: Google OAuth (for Google Sheets integration)
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
# GOOGLE_REDIRECT_URI=

# Optional: Airtable OAuth
# AIRTABLE_CLIENT_ID=
# AIRTABLE_REDIRECT_URI=

# Telemetry (helps improve Maxun)
MAXUN_TELEMETRY=true
EOF
    
    echo -e "${GREEN}✓ Environment file created${NC}"
    echo -e "${YELLOW}Note: Review .env file to customize settings if needed${NC}"
    echo ""
}

# Pull and start services
start_services() {
    echo -e "${BLUE}Starting Maxun services...${NC}"
    
    echo -e "${YELLOW}Pulling latest Docker images...${NC}"
    docker-compose pull
    
    echo -e "${YELLOW}Starting containers...${NC}"
    docker-compose up -d
    
    echo -e "${GREEN}✓ Services started${NC}"
    echo ""
}

# Wait for services to be ready
wait_for_services() {
    echo -e "${BLUE}Waiting for services to be ready...${NC}"
    
    local max_attempts=30
    local attempt=0
    
    while [ $attempt -lt $max_attempts ]; do
        if curl -sf http://localhost:8080/health > /dev/null 2>&1; then
            echo -e "${GREEN}✓ Backend is ready${NC}"
            break
        fi
        
        echo -e "${YELLOW}Waiting for backend... (attempt $((attempt + 1))/${max_attempts})${NC}"
        sleep 2
        ((attempt++))
    done
    
    if [ $attempt -eq $max_attempts ]; then
        echo -e "${RED}✗ Backend failed to start${NC}"
        echo -e "${YELLOW}Check logs with: docker-compose logs backend${NC}"
        return 1
    fi
    
    echo ""
}

# Print access information
print_access_info() {
    echo -e "${GREEN}"
    cat << "EOF"
╔═══════════════════════════════════════════════════════════╗
║                    Deployment Complete!                   ║
╚═══════════════════════════════════════════════════════════╝
EOF
    echo -e "${NC}"
    
    echo -e "${BLUE}Access URLs:${NC}"
    echo -e "  • Frontend:      ${GREEN}http://localhost:5173${NC}"
    echo -e "  • Backend API:   ${GREEN}http://localhost:8080${NC}"
    echo -e "  • MinIO Console: ${GREEN}http://localhost:9001${NC}"
    echo ""
    
    echo -e "${BLUE}Next Steps:${NC}"
    echo -e "  1. Open ${GREEN}http://localhost:5173${NC} in your browser"
    echo -e "  2. Create an account"
    echo -e "  3. Generate an API key in Settings → API Keys"
    echo -e "  4. Create your first robot by recording a workflow"
    echo -e "  5. Use the examples in ${GREEN}./examples/${NC} directory"
    echo ""
    
    echo -e "${BLUE}Quick Start Commands:${NC}"
    echo -e "  ${YELLOW}# View logs${NC}"
    echo -e "  docker-compose logs -f"
    echo ""
    echo -e "  ${YELLOW}# Stop services${NC}"
    echo -e "  docker-compose down"
    echo ""
    echo -e "  ${YELLOW}# Restart services${NC}"
    echo -e "  docker-compose restart"
    echo ""
    echo -e "  ${YELLOW}# Run Python example${NC}"
    echo -e "  cd examples && python chat_automation_python.py"
    echo ""
    echo -e "  ${YELLOW}# Run Node.js example${NC}"
    echo -e "  cd examples && node chat_automation_node.js"
    echo ""
    
    echo -e "${BLUE}Documentation:${NC}"
    echo -e "  • Full Guide:     ${GREEN}./docs/BROWSER_AUTOMATION_CHAT.md${NC}"
    echo -e "  • Examples:       ${GREEN}./examples/README.md${NC}"
    echo -e "  • Official Docs:  ${GREEN}https://docs.maxun.dev${NC}"
    echo ""
    
    echo -e "${BLUE}Support:${NC}"
    echo -e "  • Discord:  ${GREEN}https://discord.gg/5GbPjBUkws${NC}"
    echo -e "  • GitHub:   ${GREEN}https://github.com/getmaxun/maxun${NC}"
    echo ""
}

# Setup example environment
setup_examples() {
    echo -e "${BLUE}Setting up examples...${NC}"
    
    if [ ! -d examples ]; then
        echo -e "${YELLOW}Examples directory not found${NC}"
        return
    fi
    
    cd examples
    
    if [ ! -f .env ]; then
        cat > .env << 'EOF'
# Maxun API Configuration
MAXUN_API_URL=http://localhost:8080/api
MAXUN_API_KEY=
MAXUN_ROBOT_ID=

# Chat Interface Credentials
CHAT_USERNAME=
CHAT_PASSWORD=
EOF
        echo -e "${GREEN}✓ Created examples/.env template${NC}"
        echo -e "${YELLOW}  Please edit examples/.env with your credentials${NC}"
    else
        echo -e "${YELLOW}examples/.env already exists${NC}"
    fi
    
    # Make bash script executable
    if [ -f chat_automation_bash.sh ]; then
        chmod +x chat_automation_bash.sh
        echo -e "${GREEN}✓ Made bash script executable${NC}"
    fi
    
    cd ..
    echo ""
}

# Main deployment function
main() {
    print_banner
    
    echo -e "${BLUE}This script will:${NC}"
    echo "  1. Check for Docker and Docker Compose"
    echo "  2. Generate secure configuration"
    echo "  3. Start Maxun services"
    echo "  4. Set up example scripts"
    echo ""
    
    read -p "Continue? (Y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        echo -e "${YELLOW}Deployment cancelled${NC}"
        exit 0
    fi
    
    check_dependencies
    setup_env
    start_services
    wait_for_services || exit 1
    setup_examples
    print_access_info
    
    echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║           Happy Automating with Maxun! 🚀                ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
}

# Run main function
main "$@"

